use std::collections::HashSet;
use std::env;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::ExitCode;

use fyr::ast::{Program, Statement};
use fyr::format::{format_program, format_source};
use fyr::{FyrError, eval, lexer, parser, repl, typecheck};

const MANIFEST_FILE: &str = "fyr.toml";
const DEFAULT_MAIN: &str = "src/main.fyr";
const DEFAULT_TEST_DIR: &str = "tests";

fn main() -> ExitCode {
    match run_cli() {
        Ok(()) => ExitCode::SUCCESS,
        Err(message) => {
            eprintln!("{message}");
            ExitCode::FAILURE
        }
    }
}

fn run_cli() -> Result<(), String> {
    let args: Vec<String> = env::args().collect();

    match args.as_slice() {
        [] => repl::start().map_err(|error| error.to_string()),
        [_] => repl::start().map_err(|error| error.to_string()),
        [_, command] if command == "repl" => repl::start().map_err(|error| error.to_string()),
        [_, command] if command == "help" || command == "--help" || command == "-h" => {
            print_help();
            Ok(())
        }
        [_, command] if command == "version" || command == "--version" || command == "-V" => {
            println!("fyr 0.1.0");
            Ok(())
        }
        [_, command] if command == "doctor" => {
            print_doctor()?;
            Ok(())
        }
        [_, command, args @ ..] if command == "init" => init_project(args),
        [_, command, args @ ..] if command == "new" => new_project(args),
        [_, command, args @ ..] if command == "build" => build_file(args),
        [_, command, args @ ..] if command == "run" => run_file(args),
        [_, command, paths @ ..] if command == "check" => check_files(paths),
        [_, command, args @ ..] if command == "fmt" => fmt_files(args),
        [_, command, paths @ ..] if command == "test" => test_files(paths),
        [_, path] if is_direct_run_path(path) => run_file(std::slice::from_ref(path)),
        [_, unknown, ..] => Err(format!(
            "unknown command '{unknown}'. Run `fyr help` for usage."
        )),
    }
}

fn is_direct_run_path(arg: &str) -> bool {
    Path::new(arg)
        .extension()
        .and_then(|extension| extension.to_str())
        == Some("fyr")
}

fn run_file(args: &[String]) -> Result<(), String> {
    let path = match args {
        [] => project_from_cwd()?.main,
        [path] => PathBuf::from(path),
        _ => return Err("fyr run expects zero or one file path".to_owned()),
    };
    let program = load_program(&path)?;
    check_program_for_path(&path, &program)?;
    let result = eval::Evaluator::new()
        .run(&program)
        .map_err(|error| format_fyr_error(&path, error))?;

    for line in result.outputs {
        println!("{line}");
    }

    Ok(())
}

fn build_file(args: &[String]) -> Result<(), String> {
    let options = parse_build_args(args)?;
    let (input, default_output) = match options.input {
        Some(path) => {
            let input = PathBuf::from(path);
            let output = default_build_output_for_file(&input)?;
            (input, output)
        }
        None => {
            let project = project_from_cwd()?;
            (project.main.clone(), project.root.join("build/main.fyr"))
        }
    };
    let output = options.output.map(PathBuf::from).unwrap_or(default_output);
    let program = load_program(&input)?;

    check_program_for_path(&input, &program)?;

    let bundled = format!(
        "# Generated by fyr build.\n# Source: {}\n{}",
        input.display(),
        format_program(&program)
    );
    write_text_file(&output, &bundled)?;
    println!("built {} -> {}", input.display(), output.display());
    Ok(())
}

fn check_files(paths: &[String]) -> Result<(), String> {
    let files = collect_source_paths_or_project(paths, "check", ProjectPathMode::SourcesAndTests)?;

    for path in files {
        let program = load_program(&path)?;
        check_program_for_path(&path, &program)?;
        println!("{}: ok", path.display());
    }

    Ok(())
}

fn test_files(paths: &[String]) -> Result<(), String> {
    let files = collect_source_paths_or_project(paths, "test", ProjectPathMode::TestsOnly)?;
    let file_count = files.len();

    for path in files {
        let program = load_program(&path)?;
        check_program_for_path(&path, &program)?;
        let result = eval::Evaluator::new()
            .run(&program)
            .map_err(|error| format_fyr_error(&path, error))?;
        for line in result.outputs {
            println!("{line}");
        }
        println!("{}: pass", path.display());
    }

    if file_count > 1 {
        println!("{file_count} test files passed");
    }

    Ok(())
}

fn fmt_files(args: &[String]) -> Result<(), String> {
    let (check, paths) = parse_fmt_args(args)?;
    let files = collect_source_paths_or_project(paths, "fmt", ProjectPathMode::SourcesAndTests)?;
    let mut unformatted = Vec::new();

    for path in files {
        let source = read_source_path(&path)?;
        let formatted = format_source(&source).map_err(|error| format_fyr_error(&path, error))?;

        if source == formatted {
            println!("{}: ok", path.display());
        } else if check {
            println!("{}: needs fmt", path.display());
            unformatted.push(path);
        } else {
            fs::write(&path, formatted)
                .map_err(|error| format!("failed to write {}: {error}", path.display()))?;
            println!("{}: formatted", path.display());
        }
    }

    if check && !unformatted.is_empty() {
        return Err(format!("{} file(s) need formatting", unformatted.len()));
    }

    Ok(())
}

fn init_project(args: &[String]) -> Result<(), String> {
    match args {
        [] => init_project_at(
            &env::current_dir().map_err(|error| format!("failed to read cwd: {error}"))?,
        ),
        [path] => init_project_at(Path::new(path)),
        _ => Err("fyr init expects zero or one project path".to_owned()),
    }
}

fn new_project(args: &[String]) -> Result<(), String> {
    match args {
        [path] => init_project_at(Path::new(path)),
        [] => Err("fyr new expects a project path".to_owned()),
        _ => Err("fyr new expects exactly one project path".to_owned()),
    }
}

fn init_project_at(root: &Path) -> Result<(), String> {
    let name = project_name(root);
    let manifest = root.join(MANIFEST_FILE);
    let main = root.join(DEFAULT_MAIN);
    let lib = root.join("src/lib.fyr");
    let test = root.join(DEFAULT_TEST_DIR).join("main.fyr");

    for path in [&manifest, &main, &lib, &test] {
        if path.exists() {
            return Err(format!("{} already exists", path.display()));
        }
    }

    write_new_file(
        &manifest,
        &format!("name = \"{name}\"\nmain = \"{DEFAULT_MAIN}\"\n"),
    )?;
    write_new_file(
        &main,
        r#"# Fyr project entry point.
import "lib.fyr"
print(greeting("Fyr"))
"#,
    )?;
    write_new_file(
        &lib,
        r#"# Shared Fyr project code.
fn greeting(name: str) -> str:
    return "Hello from " + name
"#,
    )?;
    write_new_file(
        &test,
        r#"# Fyr project smoke tests.
import "../src/lib.fyr"
assert(greeting("Fyr") == "Hello from Fyr")
assert(reverse("Fyr") == "ryF")
assert(split("fast secure simple", " ") == ["fast", "secure", "simple"])
assert(join(["fast", "secure", "simple"], "-") == "fast-secure-simple")
"#,
    )?;

    println!("created Fyr project at {}", root.display());
    println!("  run:   fyr run");
    println!("  check: fyr check");
    println!("  test:  fyr test");
    println!("  fmt:   fyr fmt --check");
    println!("  build: fyr build");
    Ok(())
}

fn parse_fmt_args(args: &[String]) -> Result<(bool, &[String]), String> {
    match args {
        [flag, paths @ ..] if flag == "--check" || flag == "-c" => Ok((true, paths)),
        [flag, ..] if flag.starts_with('-') => Err(format!("unknown fyr fmt option '{flag}'")),
        paths => Ok((false, paths)),
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
struct BuildOptions<'a> {
    input: Option<&'a str>,
    output: Option<&'a str>,
}

fn parse_build_args(args: &[String]) -> Result<BuildOptions<'_>, String> {
    let mut input = None;
    let mut output = None;
    let mut index = 0;

    while index < args.len() {
        match args[index].as_str() {
            "--out" | "-o" => {
                index += 1;
                if index >= args.len() {
                    return Err("fyr build --out expects a path".to_owned());
                }
                if output.replace(args[index].as_str()).is_some() {
                    return Err("fyr build received --out more than once".to_owned());
                }
            }
            flag if flag.starts_with('-') => {
                return Err(format!("unknown fyr build option '{flag}'"));
            }
            path => {
                if input.replace(path).is_some() {
                    return Err("fyr build expects at most one input file".to_owned());
                }
            }
        }
        index += 1;
    }

    Ok(BuildOptions { input, output })
}

fn default_build_output_for_file(input: &Path) -> Result<PathBuf, String> {
    let parent = input.parent().unwrap_or_else(|| Path::new("."));
    let stem = input
        .file_stem()
        .and_then(|stem| stem.to_str())
        .ok_or_else(|| format!("failed to derive build output for {}", input.display()))?;
    Ok(parent.join(format!("{stem}.bundle.fyr")))
}

#[derive(Debug, Clone)]
struct Project {
    root: PathBuf,
    main: PathBuf,
}

#[derive(Debug, Clone, Copy)]
enum ProjectPathMode {
    SourcesAndTests,
    TestsOnly,
}

fn collect_source_paths_or_project(
    paths: &[String],
    command: &str,
    mode: ProjectPathMode,
) -> Result<Vec<PathBuf>, String> {
    if paths.is_empty() {
        return collect_project_source_paths(command, mode);
    }

    collect_source_paths(paths, command)
}

fn collect_project_source_paths(
    command: &str,
    mode: ProjectPathMode,
) -> Result<Vec<PathBuf>, String> {
    let project = project_from_cwd()?;
    collect_project_source_paths_for(&project, command, mode)
}

fn collect_project_source_paths_for(
    project: &Project,
    command: &str,
    mode: ProjectPathMode,
) -> Result<Vec<PathBuf>, String> {
    let mut files = Vec::new();

    match mode {
        ProjectPathMode::SourcesAndTests => {
            collect_source_path(&project.main, &mut files)?;
            let src = project.root.join("src");
            if src.exists() {
                collect_source_dir(&src, &mut files)?;
            }
            let tests = project.root.join(DEFAULT_TEST_DIR);
            if tests.exists() {
                collect_source_dir(&tests, &mut files)?;
            }
        }
        ProjectPathMode::TestsOnly => {
            let tests = project.root.join(DEFAULT_TEST_DIR);
            if !tests.exists() {
                return Err(format!(
                    "fyr {command} found no tests directory in project {}",
                    project.root.display()
                ));
            }
            collect_source_dir(&tests, &mut files)?;
        }
    }

    files.sort();
    files.dedup();

    if files.is_empty() {
        return Err(format!(
            "fyr {command} found no .fyr files in project {}",
            project.root.display()
        ));
    }

    Ok(files)
}

fn project_from_cwd() -> Result<Project, String> {
    let cwd = env::current_dir().map_err(|error| format!("failed to read cwd: {error}"))?;
    let root = find_project_root(&cwd)
        .ok_or_else(|| format!("no {MANIFEST_FILE} found from {}", cwd.display()))?;
    read_project_manifest(&root)
}

fn find_project_root(start: &Path) -> Option<PathBuf> {
    let mut current = if start.is_file() {
        start.parent()
    } else {
        Some(start)
    };

    while let Some(path) = current {
        if path.join(MANIFEST_FILE).is_file() {
            return Some(path.to_path_buf());
        }
        current = path.parent();
    }

    None
}

fn read_project_manifest(root: &Path) -> Result<Project, String> {
    let manifest = root.join(MANIFEST_FILE);
    let source = read_source_path(&manifest)?;
    let main = manifest_value(&source, "main").unwrap_or_else(|| DEFAULT_MAIN.to_owned());
    let main_path = Path::new(&main);

    if main_path.is_absolute() {
        return Err(format!(
            "{} main path must be relative, found {main}",
            manifest.display()
        ));
    }

    Ok(Project {
        root: root.to_path_buf(),
        main: root.join(main_path),
    })
}

fn manifest_value(source: &str, key: &str) -> Option<String> {
    for raw_line in source.lines() {
        let line = raw_line.split('#').next().unwrap_or_default().trim();
        let Some((left, right)) = line.split_once('=') else {
            continue;
        };
        if left.trim() != key {
            continue;
        }

        let value = right.trim();
        if let Some(value) = value
            .strip_prefix('"')
            .and_then(|value| value.strip_suffix('"'))
        {
            return Some(value.to_owned());
        }

        return Some(value.to_owned());
    }

    None
}

#[derive(Default)]
struct ImportResolver {
    active: Vec<PathBuf>,
    loaded: HashSet<PathBuf>,
    project_root: Option<PathBuf>,
}

impl ImportResolver {
    fn new(project_root: Option<PathBuf>) -> Self {
        Self {
            active: Vec::new(),
            loaded: HashSet::new(),
            project_root,
        }
    }

    fn load_program(&mut self, path: &Path) -> Result<Program, String> {
        let path = path
            .canonicalize()
            .map_err(|error| format!("failed to resolve {}: {error}", path.display()))?;
        self.ensure_project_import_allowed(&path)?;

        if let Some(index) = self.active.iter().position(|active| active == &path) {
            let mut cycle = self.active[index..]
                .iter()
                .map(|path| path.display().to_string())
                .collect::<Vec<_>>();
            cycle.push(path.display().to_string());
            return Err(format!("import cycle detected: {}", cycle.join(" -> ")));
        }

        if self.loaded.contains(&path) {
            return Ok(Program {
                statements: Vec::new(),
            });
        }

        let source = read_source_path(&path)?;
        let tokens = lexer::lex(&source).map_err(|error| format_fyr_error(&path, error))?;
        let mut program = parser::parse(&tokens).map_err(|error| format_fyr_error(&path, error))?;
        for statement in &mut program.statements {
            statement.set_source_path_recursive(&path);
        }
        let base = path
            .parent()
            .ok_or_else(|| format!("failed to find parent directory for {}", path.display()))?
            .to_path_buf();
        let mut statements = Vec::new();

        self.active.push(path.clone());
        for statement in program.statements {
            if let Statement::Import {
                path: import_path, ..
            } = &statement
            {
                let resolved = resolve_import_path(&base, import_path)
                    .map_err(|message| format_statement_error(&path, &statement, message))?;
                let resolved = resolved.canonicalize().map_err(|error| {
                    format_statement_error(
                        &path,
                        &statement,
                        format!("failed to resolve import \"{import_path}\": {error}"),
                    )
                })?;
                self.ensure_project_import_allowed(&resolved)
                    .map_err(|message| format_statement_error(&path, &statement, message))?;
                statements.extend(self.load_program(&resolved)?.statements);
            } else {
                statements.push(statement);
            }
        }
        self.active.pop();
        self.loaded.insert(path);

        Ok(Program { statements })
    }

    fn ensure_project_import_allowed(&self, path: &Path) -> Result<(), String> {
        if let Some(project_root) = &self.project_root
            && !path.starts_with(project_root)
        {
            return Err(format!(
                "import {} escapes project root {}",
                path.display(),
                project_root.display()
            ));
        }

        Ok(())
    }
}

fn load_program(path: &Path) -> Result<Program, String> {
    let project_root = import_project_root_for(path)?;
    ImportResolver::new(project_root).load_program(path)
}

fn check_program_for_path(path: &Path, program: &Program) -> Result<(), String> {
    typecheck::check(program).map_err(|error| format_fyr_error(path, error))
}

fn format_statement_error(
    fallback_path: &Path,
    statement: &Statement,
    message: impl Into<String>,
) -> String {
    let error =
        FyrError::new(message, statement.span()).with_fallback_source_path(statement.source_path());
    format_fyr_error(fallback_path, error)
}

fn format_fyr_error(path: &Path, error: FyrError) -> String {
    let path = error.file.as_deref().unwrap_or(path);
    if error.line == 0 && error.column == 0 {
        format!("{}: {}", path.display(), error.message)
    } else {
        let mut message = format!(
            "{}:{}:{}: {}",
            path.display(),
            error.line,
            error.column,
            error.message
        );
        if let Some(snippet) = source_snippet(path, error.line, error.column) {
            message.push('\n');
            message.push_str(&snippet);
        }
        message
    }
}

fn source_snippet(path: &Path, line: usize, column: usize) -> Option<String> {
    let source = fs::read_to_string(path).ok()?;
    let lines = source.lines().collect::<Vec<_>>();
    let target_index = line.checked_sub(1)?;
    let target_line = *lines.get(target_index)?;
    let start = target_index.saturating_sub(1);
    let end = (target_index + 1).min(lines.len().saturating_sub(1));
    let gutter_width = (end + 1).to_string().len();
    let mut snippet = format!("{space:>width$} |", space = "", width = gutter_width);

    for (index, line_text) in lines.iter().enumerate().take(end + 1).skip(start) {
        let line_number = index + 1;
        snippet.push('\n');
        snippet.push_str(&format!(
            "{line_number:>width$} | {line_text}",
            width = gutter_width
        ));

        if index == target_index {
            let caret_offset = column.saturating_sub(1).min(target_line.chars().count());
            let caret_width = target_line
                .chars()
                .count()
                .saturating_sub(caret_offset)
                .max(1);
            snippet.push('\n');
            snippet.push_str(&format!(
                "{space:>width$} | {padding}{carets}",
                space = "",
                width = gutter_width,
                padding = " ".repeat(caret_offset),
                carets = "^".repeat(caret_width),
            ));
        }
    }

    Some(snippet)
}

fn import_project_root_for(path: &Path) -> Result<Option<PathBuf>, String> {
    find_project_root(path)
        .map(|root| {
            root.canonicalize().map_err(|error| {
                format!("failed to resolve project root {}: {error}", root.display())
            })
        })
        .transpose()
}

fn resolve_import_path(base: &Path, import_path: &str) -> Result<PathBuf, String> {
    if import_path.trim().is_empty() {
        return Err("import path must not be empty".to_owned());
    }

    let path = Path::new(import_path);
    if path.is_absolute() {
        return Err(format!("import path must be relative, found {import_path}"));
    }

    if path.extension().and_then(|extension| extension.to_str()) != Some("fyr") {
        return Err(format!("import path must end in .fyr, found {import_path}"));
    }

    Ok(base.join(path))
}

fn collect_source_paths(paths: &[String], command: &str) -> Result<Vec<PathBuf>, String> {
    if paths.is_empty() {
        return Err(format!("fyr {command} expects at least one path"));
    }

    let mut files = Vec::new();
    for path in paths {
        collect_source_path(Path::new(path), &mut files)?;
    }

    files.sort();
    files.dedup();

    if files.is_empty() {
        return Err(format!("fyr {command} found no .fyr files"));
    }

    Ok(files)
}

fn collect_source_path(path: &Path, files: &mut Vec<PathBuf>) -> Result<(), String> {
    if path.is_file() {
        files.push(path.to_path_buf());
        return Ok(());
    }

    if path.is_dir() {
        collect_source_dir(path, files)?;
        return Ok(());
    }

    Err(format!("{} does not exist", path.display()))
}

fn collect_source_dir(path: &Path, files: &mut Vec<PathBuf>) -> Result<(), String> {
    let mut entries = fs::read_dir(path)
        .map_err(|error| format!("failed to read {}: {error}", path.display()))?
        .collect::<Result<Vec<_>, _>>()
        .map_err(|error| format!("failed to read {}: {error}", path.display()))?;
    entries.sort_by_key(|entry| entry.path());

    for entry in entries {
        let path = entry.path();
        if path.is_dir() {
            collect_source_dir(&path, files)?;
        } else if path.extension().and_then(|extension| extension.to_str()) == Some("fyr") {
            files.push(path);
        }
    }

    Ok(())
}

fn read_source_path(path: &Path) -> Result<String, String> {
    fs::read_to_string(path).map_err(|error| format!("failed to read {}: {error}", path.display()))
}

fn write_new_file(path: &Path, contents: &str) -> Result<(), String> {
    write_text_file(path, contents)
}

fn write_text_file(path: &Path, contents: &str) -> Result<(), String> {
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)
            .map_err(|error| format!("failed to create {}: {error}", parent.display()))?;
    }

    fs::write(path, contents)
        .map_err(|error| format!("failed to write {}: {error}", path.display()))
}

fn project_name(root: &Path) -> String {
    let fallback = "fyr-project";
    let raw = root
        .file_name()
        .and_then(|name| name.to_str())
        .filter(|name| !name.is_empty())
        .unwrap_or(fallback);
    let mut name = String::new();

    for ch in raw.chars() {
        if ch.is_ascii_alphanumeric() || ch == '-' || ch == '_' {
            name.push(ch);
        } else {
            name.push('-');
        }
    }

    let name = name.trim_matches('-');
    if name.is_empty() {
        fallback.to_owned()
    } else {
        name.to_owned()
    }
}

fn print_help() {
    println!("Fyr programming language bootstrap");
    println!();
    println!("Usage:");
    println!("  fyr              Start the REPL");
    println!("  fyr <file.fyr>   Run a Fyr source file");
    println!("  fyr repl         Start the REPL");
    println!("  fyr init [dir]   Create a Fyr project in a directory");
    println!("  fyr new <dir>    Create a Fyr project in a new directory");
    println!("  fyr build [file] Build a checked, import-flattened Fyr bundle");
    println!("  fyr build --out <file> [input] Write the bundle to a custom path");
    println!("  fyr run [file]   Run a Fyr source file or project main");
    println!("  fyr check [path...] Parse-check Fyr files, directories, or project");
    println!("  fyr fmt [path...]   Format Fyr files, directories, or project");
    println!("  fyr fmt --check [path...] Check Fyr formatting without writing");
    println!("  fyr test [path...]  Run Fyr assertion files, directories, or project tests");
    println!("  fyr doctor       Show command/install diagnostics");
    println!("  fyr version      Print the Fyr version");
    println!();
    println!("REPL commands:");
    println!("  :help            Show REPL help");
    println!("  :load <file>     Run a Fyr file in the current REPL session");
    println!("  :history         Show accepted REPL source");
    println!("  :reset           Clear REPL bindings and history");
    println!("  :quit            Exit the REPL");
}

fn print_doctor() -> Result<(), String> {
    let exe = env::current_exe().map_err(|error| format!("failed to locate fyr: {error}"))?;
    let cwd = env::current_dir().map_err(|error| format!("failed to read cwd: {error}"))?;
    let exe_dir = exe
        .parent()
        .ok_or_else(|| "failed to locate fyr binary directory".to_owned())?;
    let path = env::var_os("PATH").unwrap_or_default();
    let on_path = env::split_paths(&path).any(|entry| same_path(&entry, exe_dir));

    println!("fyr doctor");
    println!("  version: 0.1.0");
    println!("  executable: {}", exe.display());
    println!("  cwd: {}", cwd.display());
    println!("  binary directory on PATH: {on_path}");

    if !on_path {
        println!("  hint: add {} to PATH", exe_dir.display());
    }

    Ok(())
}

fn same_path(left: &Path, right: &Path) -> bool {
    match (left.canonicalize(), right.canonicalize()) {
        (Ok(left), Ok(right)) => left == right,
        _ => left == right,
    }
}

#[cfg(test)]
mod tests {
    use std::process;

    use super::*;

    #[test]
    fn init_project_creates_manifest_main_and_tests_without_overwriting() {
        let root = temp_project_dir("init");

        init_project_at(&root).expect("project should initialize");

        assert!(root.join(MANIFEST_FILE).is_file());
        assert!(root.join(DEFAULT_MAIN).is_file());
        assert!(root.join("src/lib.fyr").is_file());
        assert!(root.join(DEFAULT_TEST_DIR).join("main.fyr").is_file());

        let project = read_project_manifest(&root).expect("manifest should load");
        assert_eq!(project.main, root.join(DEFAULT_MAIN));

        let error = init_project_at(&root).expect_err("init should not overwrite project files");
        assert!(error.contains("already exists"));

        fs::remove_dir_all(root).expect("test project should clean up");
    }

    #[test]
    fn find_project_root_walks_up_from_nested_directories() {
        let root = temp_project_dir("nested");
        init_project_at(&root).expect("project should initialize");
        let nested = root.join("src").join("deeper");
        fs::create_dir_all(&nested).expect("nested dir should create");

        let found = find_project_root(&nested).expect("project root should be discovered");

        assert_eq!(found, root);
        fs::remove_dir_all(found).expect("test project should clean up");
    }

    #[test]
    fn project_default_paths_include_sources_and_tests() {
        let root = temp_project_dir("paths");
        init_project_at(&root).expect("project should initialize");
        let project = read_project_manifest(&root).expect("manifest should load");

        let all =
            collect_project_source_paths_for(&project, "check", ProjectPathMode::SourcesAndTests)
                .expect("project source paths should collect");
        let tests = collect_project_source_paths_for(&project, "test", ProjectPathMode::TestsOnly)
            .expect("project tests should collect");

        assert!(all.contains(&root.join(DEFAULT_MAIN)));
        assert!(all.contains(&root.join("src/lib.fyr")));
        assert!(all.contains(&root.join(DEFAULT_TEST_DIR).join("main.fyr")));
        assert_eq!(tests, vec![root.join(DEFAULT_TEST_DIR).join("main.fyr")]);

        fs::remove_dir_all(root).expect("test project should clean up");
    }

    #[test]
    fn manifest_main_defaults_and_rejects_absolute_paths() {
        let root = temp_project_dir("manifest");
        fs::create_dir_all(&root).expect("project dir should create");
        fs::write(root.join(MANIFEST_FILE), "name = \"demo\"\n").expect("manifest should write");

        let project = read_project_manifest(&root).expect("default main should load");
        assert_eq!(project.main, root.join(DEFAULT_MAIN));

        fs::write(root.join(MANIFEST_FILE), "main = \"/tmp/main.fyr\"\n")
            .expect("manifest should write");
        let error = read_project_manifest(&root).expect_err("absolute main path should fail");
        assert!(error.contains("main path must be relative"));

        fs::remove_dir_all(root).expect("test project should clean up");
    }

    #[test]
    fn project_name_is_safe_for_manifest_text() {
        assert_eq!(project_name(Path::new("hello fyr!")), "hello-fyr");
        assert_eq!(project_name(Path::new("fyr_project")), "fyr_project");
    }

    #[test]
    fn direct_run_paths_are_fyr_files() {
        assert!(is_direct_run_path("hello.fyr"));
        assert!(is_direct_run_path("/tmp/project/src/main.fyr"));
        assert!(!is_direct_run_path("run"));
        assert!(!is_direct_run_path("hello.txt"));
    }

    #[test]
    fn import_resolver_loads_relative_files_before_importer() {
        let root = temp_project_dir("imports");
        fs::create_dir_all(root.join("src")).expect("source dir should create");
        fs::write(
            root.join("src/lib.fyr"),
            r#"
fn double(value: i64) -> i64:
    return value * 2
"#,
        )
        .expect("lib should write");
        fs::write(
            root.join("src/main.fyr"),
            r#"
import "lib.fyr"
print(double(21))
"#,
        )
        .expect("main should write");

        let program = load_program(&root.join("src/main.fyr")).expect("imports should resolve");
        typecheck::check(&program).expect("resolved program should typecheck");
        let result = eval::Evaluator::new()
            .run(&program)
            .expect("resolved program should run");

        assert_eq!(result.outputs, vec!["42"]);
        fs::remove_dir_all(root).expect("test project should clean up");
    }

    #[test]
    fn import_resolver_deduplicates_shared_imports() {
        let root = temp_project_dir("import_dedup");
        fs::create_dir_all(root.join("src")).expect("source dir should create");
        fs::write(
            root.join("src/lib.fyr"),
            r#"
fn answer() -> i64:
    return 42
"#,
        )
        .expect("lib should write");
        fs::write(root.join("src/a.fyr"), "import \"lib.fyr\"\n").expect("a should write");
        fs::write(root.join("src/b.fyr"), "import \"lib.fyr\"\n").expect("b should write");
        fs::write(
            root.join("src/main.fyr"),
            r#"
import "a.fyr"
import "b.fyr"
answer()
"#,
        )
        .expect("main should write");

        let program = load_program(&root.join("src/main.fyr")).expect("imports should resolve");
        typecheck::check(&program).expect("deduped imports should typecheck");

        fs::remove_dir_all(root).expect("test project should clean up");
    }

    #[test]
    fn import_resolver_rejects_cycles() {
        let root = temp_project_dir("import_cycle");
        fs::create_dir_all(root.join("src")).expect("source dir should create");
        fs::write(root.join("src/a.fyr"), "import \"b.fyr\"\n").expect("a should write");
        fs::write(root.join("src/b.fyr"), "import \"a.fyr\"\n").expect("b should write");

        let error = load_program(&root.join("src/a.fyr")).expect_err("cycle should fail");

        assert!(error.contains("import cycle detected"));
        fs::remove_dir_all(root).expect("test project should clean up");
    }

    #[test]
    fn import_paths_must_be_relative_fyr_files() {
        let root = temp_project_dir("import_paths");
        fs::create_dir_all(&root).expect("dir should create");

        let absolute =
            resolve_import_path(&root, "/tmp/lib.fyr").expect_err("absolute imports should fail");
        assert!(absolute.contains("must be relative"));

        let extension =
            resolve_import_path(&root, "lib.txt").expect_err("wrong extension should fail");
        assert!(extension.contains("must end in .fyr"));

        fs::remove_dir_all(root).expect("test project should clean up");
    }

    #[test]
    fn fyr_errors_format_with_file_paths_and_real_spans() {
        let path = Path::new("src/main.fyr");

        let real = format_fyr_error(path, FyrError::new("boom", fyr::span::Span::new(2, 3)));
        let virtual_span = format_fyr_error(
            path,
            FyrError::new("type checker context", fyr::span::Span::new(0, 0)),
        );

        assert_eq!(real, "src/main.fyr:2:3: boom");
        assert_eq!(virtual_span, "src/main.fyr: type checker context");
    }

    #[test]
    fn fyr_errors_include_source_snippets_when_file_is_available() {
        let root = temp_project_dir("error_snippet");
        fs::create_dir_all(&root).expect("dir should create");
        let path = root.join("main.fyr");
        fs::write(&path, "let value: i64 = false\n").expect("source should write");

        let message = format_fyr_error(
            &path,
            FyrError::new("binding 'value' expected i64", fyr::span::Span::new(1, 5)),
        );

        assert!(message.contains("1 | let value: i64 = false"));
        assert!(message.contains("  |     ^"));
        fs::remove_dir_all(root).expect("test project should clean up");
    }

    #[test]
    fn source_snippets_include_neighbor_lines_and_caret_spans() {
        let root = temp_project_dir("error_context_snippet");
        fs::create_dir_all(&root).expect("dir should create");
        let path = root.join("main.fyr");
        fs::write(&path, "let ok = true\nlet value: i64 = false\nprint(ok)\n")
            .expect("source should write");

        let message = format_fyr_error(
            &path,
            FyrError::new("binding 'value' expected i64", fyr::span::Span::new(2, 5)),
        );

        assert!(message.contains("1 | let ok = true"));
        assert!(message.contains("2 | let value: i64 = false"));
        assert!(message.contains("  |     ^^^^^"));
        assert!(message.contains("3 | print(ok)"));
        fs::remove_dir_all(root).expect("test project should clean up");
    }

    #[test]
    fn import_parse_errors_include_imported_file_path() {
        let root = temp_project_dir("import_parse_path");
        fs::create_dir_all(root.join("src")).expect("source dir should create");
        fs::write(root.join("src/lib.fyr"), "let = 3\n").expect("lib should write");
        fs::write(root.join("src/main.fyr"), "import \"lib.fyr\"\n").expect("main should write");

        let error = load_program(&root.join("src/main.fyr")).expect_err("import parse should fail");

        assert!(error.contains(&root.join("src/lib.fyr").display().to_string()));
        assert!(error.contains(":1:"));
        assert!(error.contains("identifier"));
        fs::remove_dir_all(root).expect("test project should clean up");
    }

    #[test]
    fn missing_imports_report_import_statement_location() {
        let root = temp_project_dir("import_missing_path");
        fs::create_dir_all(root.join("src")).expect("source dir should create");
        let main = root.join("src/main.fyr");
        fs::write(&main, "import \"missing.fyr\"\n").expect("main should write");

        let error = load_program(&main).expect_err("missing import should fail");

        assert!(error.contains(&main.display().to_string()));
        assert!(error.contains(":1:1:"));
        assert!(error.contains("failed to resolve import \"missing.fyr\""));
        assert!(error.contains("1 | import \"missing.fyr\""));
        assert!(error.contains("  | ^"));
        fs::remove_dir_all(root).expect("test project should clean up");
    }

    #[test]
    fn invalid_import_paths_report_import_statement_location() {
        let root = temp_project_dir("import_invalid_path");
        fs::create_dir_all(root.join("src")).expect("source dir should create");
        let main = root.join("src/main.fyr");
        fs::write(&main, "import \"lib.txt\"\n").expect("main should write");

        let error = load_program(&main).expect_err("invalid import should fail");

        assert!(error.contains(&main.display().to_string()));
        assert!(error.contains(":1:1:"));
        assert!(error.contains("import path must end in .fyr"));
        assert!(error.contains("1 | import \"lib.txt\""));
        assert!(error.contains("  | ^"));
        fs::remove_dir_all(root).expect("test project should clean up");
    }

    #[test]
    fn fmt_errors_include_file_path() {
        let root = temp_project_dir("fmt_error_path");
        fs::create_dir_all(&root).expect("dir should create");
        let path = root.join("broken.fyr");
        fs::write(&path, "let = 3\n").expect("source should write");
        let args = vec![path.display().to_string()];

        let error = fmt_files(&args).expect_err("formatting invalid source should fail");

        assert!(error.contains(&path.display().to_string()));
        assert!(error.contains(":1:"));
        assert!(error.contains("identifier"));
        fs::remove_dir_all(root).expect("test project should clean up");
    }

    #[test]
    fn check_type_errors_include_file_path_and_statement_span() {
        let root = temp_project_dir("check_error_path");
        fs::create_dir_all(&root).expect("dir should create");
        let path = root.join("broken.fyr");
        fs::write(&path, "let value: i64 = false\n").expect("source should write");
        let args = vec![path.display().to_string()];

        let error = check_files(&args).expect_err("type error should fail");

        assert!(error.contains(&path.display().to_string()));
        assert!(error.contains(":1:1:"));
        assert!(error.contains("binding 'value' expected i64"));
        assert!(error.contains("1 | let value: i64 = false"));
        assert!(error.contains("  | ^"));
        fs::remove_dir_all(root).expect("test project should clean up");
    }

    #[test]
    fn imported_type_errors_include_imported_file_path() {
        let root = temp_project_dir("import_type_error_path");
        fs::create_dir_all(root.join("src")).expect("source dir should create");
        let lib = root.join("src/lib.fyr");
        let main = root.join("src/main.fyr");
        fs::write(&lib, "let value: i64 = false\n").expect("lib should write");
        fs::write(&main, "import \"lib.fyr\"\n").expect("main should write");
        let args = vec![main.display().to_string()];

        let error = check_files(&args).expect_err("imported type error should fail");

        assert!(error.contains(&lib.display().to_string()));
        assert!(error.contains(":1:1:"));
        assert!(error.contains("binding 'value' expected i64"));
        assert!(error.contains("1 | let value: i64 = false"));
        assert!(error.contains("  | ^"));
        fs::remove_dir_all(root).expect("test project should clean up");
    }

    #[test]
    fn imported_match_arm_errors_include_imported_file_path() {
        let root = temp_project_dir("import_match_arm_error_path");
        fs::create_dir_all(root.join("src")).expect("source dir should create");
        let lib = root.join("src/lib.fyr");
        let main = root.join("src/main.fyr");
        fs::write(
            &lib,
            r#"enum Status:
    Ready
    Failed

fn label(status: Status) -> str:
    return match status:
        Status.Ready:
            let value: i64 = false
            "ready"
        Status.Failed:
            "failed"
"#,
        )
        .expect("lib should write");
        fs::write(&main, "import \"lib.fyr\"\n").expect("main should write");
        let args = vec![main.display().to_string()];

        let error = check_files(&args).expect_err("imported match arm error should fail");

        assert!(error.contains(&lib.display().to_string()));
        assert!(error.contains(":8:"));
        assert!(error.contains("binding 'value' expected i64"));
        assert!(error.contains("8 |             let value: i64 = false"));
        fs::remove_dir_all(root).expect("test project should clean up");
    }

    #[test]
    fn imported_runtime_errors_include_imported_file_path() {
        let root = temp_project_dir("import_runtime_error_path");
        fs::create_dir_all(root.join("src")).expect("source dir should create");
        let lib = root.join("src/lib.fyr");
        let main = root.join("src/main.fyr");
        fs::write(&lib, "1 / 0\n").expect("lib should write");
        fs::write(&main, "import \"lib.fyr\"\n").expect("main should write");
        let args = vec![main.display().to_string()];

        let error = run_file(&args).expect_err("imported runtime error should fail");

        assert!(error.contains(&lib.display().to_string()));
        assert!(error.contains(":1:1:"));
        assert!(error.contains("division by zero"));
        assert!(error.contains("1 | 1 / 0"));
        assert!(error.contains("  | ^"));
        fs::remove_dir_all(root).expect("test project should clean up");
    }

    #[test]
    fn project_imports_can_cross_between_tests_and_src_inside_root() {
        let root = temp_project_dir("import_inside_root");
        init_project_at(&root).expect("project should initialize");

        let program =
            load_program(&root.join("tests/main.fyr")).expect("project test import should resolve");
        typecheck::check(&program).expect("project test import should typecheck");

        fs::remove_dir_all(root).expect("test project should clean up");
    }

    #[test]
    fn project_imports_cannot_escape_project_root() {
        let root = temp_project_dir("import_escape");
        init_project_at(&root).expect("project should initialize");
        let outside_name = format!("outside_{}.fyr", process::id());
        let outside = root
            .parent()
            .expect("test project should have a parent")
            .join(&outside_name);
        fs::write(
            &outside,
            r#"
fn outside() -> i64:
    return 42
"#,
        )
        .expect("outside file should write");
        fs::write(
            root.join("src/main.fyr"),
            format!("import \"../../{outside_name}\"\noutside()\n"),
        )
        .expect("main should write");

        let error =
            load_program(&root.join("src/main.fyr")).expect_err("escaping import should fail");

        assert!(error.contains("escapes project root"));
        assert!(error.contains(&root.join("src/main.fyr").display().to_string()));
        assert!(error.contains("1 | import"));
        assert!(error.contains("  | ^"));
        fs::remove_file(outside).expect("outside file should clean up");
        fs::remove_dir_all(root).expect("test project should clean up");
    }

    #[test]
    fn parses_build_arguments() {
        let none = parse_build_args(&[]).expect("empty build args should parse");
        assert_eq!(
            none,
            BuildOptions {
                input: None,
                output: None
            }
        );

        let args = vec![
            "--out".to_owned(),
            "dist/app.fyr".to_owned(),
            "src/main.fyr".to_owned(),
        ];
        let parsed = parse_build_args(&args).expect("build args should parse");
        assert_eq!(
            parsed,
            BuildOptions {
                input: Some("src/main.fyr"),
                output: Some("dist/app.fyr")
            }
        );

        let duplicate = vec!["a.fyr".to_owned(), "b.fyr".to_owned()];
        let error = parse_build_args(&duplicate).expect_err("duplicate inputs should fail");
        assert!(error.contains("at most one input"));
    }

    #[test]
    fn derives_default_build_output_for_file() {
        let output =
            default_build_output_for_file(Path::new("src/main.fyr")).expect("output should derive");

        assert_eq!(output, PathBuf::from("src/main.bundle.fyr"));
    }

    #[test]
    fn build_command_writes_import_flattened_bundle() {
        let root = temp_project_dir("build");
        fs::create_dir_all(root.join("src")).expect("source dir should create");
        fs::write(
            root.join("src/lib.fyr"),
            r#"
fn greeting(name: str) -> str:
    return "Hello from " + name
"#,
        )
        .expect("lib should write");
        fs::write(
            root.join("src/main.fyr"),
            r#"
import "lib.fyr"
print(greeting("Fyr"))
"#,
        )
        .expect("main should write");
        let output = root.join("dist/app.fyr");
        let args = vec![
            "--out".to_owned(),
            output.display().to_string(),
            root.join("src/main.fyr").display().to_string(),
        ];

        build_file(&args).expect("build should pass");

        let bundled = fs::read_to_string(&output).expect("bundle should write");
        assert!(bundled.contains("# Generated by fyr build."));
        assert!(bundled.contains("fn greeting(name: str) -> str:"));
        assert!(!bundled.contains("import \"lib.fyr\""));

        let program = load_program(&output).expect("bundle should load");
        typecheck::check(&program).expect("bundle should typecheck");
        let result = eval::Evaluator::new()
            .run(&program)
            .expect("bundle should run");
        assert_eq!(result.outputs, vec!["Hello from Fyr"]);

        fs::remove_dir_all(root).expect("test project should clean up");
    }

    fn temp_project_dir(label: &str) -> PathBuf {
        let root = env::temp_dir().join(format!("fyr_cli_{label}_{}", process::id()));
        let _ = fs::remove_dir_all(&root);
        root
    }
}
